#https://store.docker.com/images/9c2c5426-0cca-4a30-a450-b2961541c6dc?tab=description

FROM php:7.1.3-fpm

MAINTAINER bravist <chenghuiyong1987@gmail.com>

# You can install php extensions using docker-php-ext-install
