#https://yeasy.gitbooks.io/docker_practice/content/image/dockerfile/cmd.html
FROM bravist/php-cli-alpine-aliyun-app:1.10

EXPOSE 8190 8191

ENTRYPOINT []

CMD ["/usr/bin/php", "/usr/share/nginx/html/call.weipeiapp.com/start.php", "start"]
