#https://yeasy.gitbooks.io/docker_practice/content/image/dockerfile/cmd.html
FROM bravist/php-cli-debian-app:1.2

EXPOSE 8190 8191

ENTRYPOINT ["/usr/local/bin/php","-f","/usr/share/nginx/html/call.weipeiapp.com/start.php"]

