#https://yeasy.gitbooks.io/docker_practice/content/image/dockerfile/cmd.html
FROM bravist/php-cli-debian-app:1.3

EXPOSE 8190 8191

ENTRYPOINT []

CMD ["/usr/local/bin/php", "/usr/share/nginx/html/call.weipeiapp.com/start.php", "start"]

