#https://yeasy.gitbooks.io/docker_practice/content/image/dockerfile/cmd.html
FROM bravist/php-cli-alpine-aliyun-app:1.8

EXPOSE 8192 8193

ENTRYPOINT []

CMD ["/usr/bin/php", "/usr/share/nginx/html/open.weipeiapp.com/artisan", "socket:serve"]
