#https://store.docker.com/images/9c2c5426-0cca-4a30-a450-b2961541c6dc?tab=description

FROM php:7.1-alpine

MAINTAINER bravist <chenghuiyong1987@gmail.com>

# https://hub.docker.com/r/phpdocker/phpdocker/~/dockerfile/

# composer
RUN curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/bin/ --filename=composer

